// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcWgPanhxztRa38FOAnPHtu-9hpSr0Tis',
    appId: '1:823769749766:web:bdced9330b9d9ed0752687',
    messagingSenderId: '823769749766',
    projectId: 'raseed-404',
    authDomain: 'raseed-404.firebaseapp.com',
    storageBucket: 'raseed-404.firebasestorage.app',
    measurementId: 'G-373LL0WE29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZxeD157iH9qsEpILq5oUV8NnRi-SIynE',
    appId: '1:823769749766:android:adee14e480941830752687',
    messagingSenderId: '823769749766',
    projectId: 'raseed-404',
    storageBucket: 'raseed-404.firebasestorage.app',
  );
}
